### ISSUE TITLE
error when click button download state picrew 

### ISSUE THREAD

**Issue by kelompoka1** [mincerafter42/picrew-downloader#2]
this log output in console  the error in line 39 👍 
![image](https://user-images.githubusercontent.com/103549374/163899872-c763b5d5-2194-4405-b5a2-1244b491b94d.png)

this line code error in line 39
![image](https://user-images.githubusercontent.com/103549374/163899928-babcfe1b-d9b1-4039-89c4-2f1c89eb6da5.png)
`	const url = new URL(state.commonImages[item.itmId][layer][colour.cId].url, baseURL); // url of image to fetch
					`
i hope you fix this extension :) 
Thanks for make this extension 👍 💯  🥇  you have helped many people 👍

**Comment by mincerafter42** [comment]
Hi, I'm not getting the same error. Can you tell me which browser you're using and which picrew you're downloading?

**Comment by kelompoka1** [comment]
H'i, I'm using chrome browser 
when i download at picrew give me error
https://picrew.me/image_maker/1532707

**Comment by Greek-Cp** [comment]
hello vivi, can you fix the bug? , I hope you can fix the bug . I want to fix it but I don't understand javascript yet, I only understand java. thank you vivi, sorry my english is bad👍

**Comment by mincerafter42** [comment]
I figured out what was causing the bug; I just need to get the new META-INF from Mozilla's add-on system, and then i can commit

**Comment by Greek-Cp** [comment]
thank's you 😀"
