### ISSUE TITLE
Add feature export layers folder

### ISSUE THREAD

**Issue by Greek-Cp** [mincerafter42/picrew-downloader#3]
Hello @mincerafter42 thank you for making piccrew downloader, this tool helped many people.
I hope you can accept the features I proposed
can you add an export folder feature with layer name? I hope you can add that feature. 

this example folder with layer name 
![image](https://user-images.githubusercontent.com/82995911/164356139-ce3cbf82-124d-44aa-b6fb-4bebd9961b65.png)
when we open the folder we can found image 
![image](https://user-images.githubusercontent.com/82995911/164356222-bf76d777-30df-4547-91a9-45d4118512a4.png)

thank's you

**Comment by mincerafter42** [comment]
hmm
am i correct in assuming this is so one doesn't have to open the full maker in an image editor (which, on my system, can take an impractically long time?)
Would making the internal folder structure of the OpenRaster file (since it is a zip file) match this folder structure be sufficient?

**Comment by Greek-Cp** [comment]
yes  you can add the export zip feature, because gimp is slowly in my laptop :"
![image](https://user-images.githubusercontent.com/82995911/164363651-c3f9ea73-bf98-43a0-b57c-952ff33f23e5.png)
like this.
thanks 👍

**Comment by mincerafter42** [comment]
Is the functionality I added now sufficient?
If you download an entire maker, open it with your zip extraction program, and look in the `data/` folder, the images should now be organized by layer

**Comment by Greek-Cp** [comment]
![image](https://user-images.githubusercontent.com/82995911/164376610-bec7949e-340d-4d8f-8584-8e295fcc0287.png)
thank's you 😄  working ❤️ 
![image](https://user-images.githubusercontent.com/82995911/164376702-1564073f-1df0-44b0-abc3-2c14e319a69b.png)
