### ISSUE TITLE
Request Feature Export with folder with name layer in Current State👍 

### ISSUE THREAD

**Issue by Greek-Cp** [mincerafter42/picrew-downloader#4]
hello can you add the feature create folder with name layer in current state ? 
![image](https://user-images.githubusercontent.com/82995911/165224884-5418871b-66dc-4721-8493-2023c9adc885.png)
like entire maker 
![image](https://user-images.githubusercontent.com/82995911/165224920-2a2b6a72-c0ae-41ad-a0a8-e5cfdbe53215.png)

👍

**Comment by mincerafter42** [comment]
Can you clarify what this would be used for?

**Comment by Greek-Cp** [comment]
I use picrew assets to test my android application. This application allows to create images from several parts. and can share it with the community, of course I do not take assets from picrew. i just try 👍
