### ISSUE TITLE
Downloader half working, getting errors

### ISSUE THREAD

**Issue by NerysRhys** [mincerafter42/picrew-downloader#6]
Hi,

I tried to use your extension with my Vivaldi browser, but I've been getting some errors about it. At first, it told me about Manifest v2 becoming soon unsupported, so I changed the version number to 3, and 'permissions' to 'host_permissions' and it didn't show up anymore.

Then it started pining me about the 106 line 'document.body.appendChild(nuxtGetter);' ?? (from the download.js)
I got this message with this:
"Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-tyKN1SrY3+Y8LI6jYpgcqB6KR4ER2saCmC5MgxBW8zE='), or a nonce ('nonce-...') is required to enable inline execution."

As I'm not a developer, I don't really understand what I should do to fix it myself, and it only worsen my problem

I'd like to say that it worked at first, I managed to get a .ora file from the 'current state' button, but not the whole maker.

Would love a little help, I recently realized that saving the whole resources of the page with the ResourceSaver extension didn't get all the makers I tried to save that way all those months ago.

**Comment by mincerafter42** [comment]
Manifest v3 is not backwards-compatible with Manifest v2. Does it work if you keep the version number as 2?

**Comment by NerysRhys** [comment]
Yes, but not with the entire maker, just the 'current state'. I've read that it might be a large file, so I waited a bit just in case it took longer than expected, but I think I can only get the 'current state' of the picrew (on Vivaldi and Opera. I can't install it on Firefox because it tells me the archive (which is a zip btw) is corrupted and I don't know how to get an xpi).

**Comment by mincerafter42** [comment]
The .xpi file is identical to the .zip file; just rename it with the .xpi extension
Downloading the entire maker can take many minutes; check the console, it should be logging the completion status as it downloads

**Comment by NerysRhys** [comment]
Sorry for the late reply (went to sleep after posting). Tried opening the console before clicking on the button, and it seemed to work better that way! Or, well, you know, now that I knew I could actually check the progress somewhere, I didn't unknowingly hit refresh in the middle of the process.

Thanks for the help! I would never have thought about that stupid console before today!
